name: Backend Tests

on:
  push:
    paths:
      - 'apps/backend/**'
      - '.github/workflows/backend-tests.yml'
      - 'pyproject.toml'
      - 'Makefile'
  pull_request:
    paths:
      - 'apps/backend/**'
      - '.github/workflows/backend-tests.yml'
      - 'pyproject.toml'
      - 'Makefile'

jobs:
  tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python -m pip install -e .[dev]

      - name: Run pytest
        run: python -m pytest --maxfail=1 --disable-warnings -q
